---
# Install OpenLightSpeed

- name: Add the OpenLiteSpeed repository for CentOS 8
  dnf:
    name: http://rpms.litespeedtech.com/centos/litespeed-repo-1.1-1.el8.noarch.rpm
    state: present
  tags: [add-repo]

- name: Install Python3 on Centos 8
  dnf:
    name: python3
    state: present
  tags: [install-pythone]

- name: Update All Packages
  dnf:
    name: "*"
    state: latest
  tags: [update-pkgs]

- name: Install OpenLiteSpeed
  dnf:
    name: openlitespeed
    state: present
  notify: restart-openlitespeed
  tags: [install-lsws]

- name: Add the EPEL repository to the system
  dnf:
    name: epel-release
    state: present
  tags: [add-epel]

- name: Install LSPHP packages from the official OpenLitespeed repository
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - "lsphp74"
    - "lsphp74-mysqlnd"
    - "lsphp74-process"
    - "lsphp74-mbstring"
    - "lsphp74-mcrypt"
    - "lsphp74-gd"
    - "lsphp74-opcache"
    - "lsphp74-bcmath"
    - "lsphp74-pdo"
    - "lsphp74-common"
    - "lsphp74-xml"
  tags: [install_php]

- name: Install the MariaDB server
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - "mariadb"
    - "mariadb-server"
  tags: [install-maria]

- name: Make sure mysqld service is running
  service:
    name: mariadb
    state: started
    enabled: yes
  tags: [start-db]

- name: Install python3-PyMySQL library
  dnf:
    name: python3-PyMySQL
    state: present
  tags: [install-python3-PyMySQL]

# Firewalld configuration
- name: Add the port '7080' to the firewalld
  firewalld:
    port: 7080/tcp
    permanent: yes
    state: enabled
  tags: [firewall]

- name: set up the OpenLitespeed dashboard authentication
  shell: sh /usr/local/lsws/admin/misc/admpass.sh
  register: adminpass
- debug: 
    var: adminpass
